# Generated by Django 4.2.1 on 2023-05-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='song_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
